---
- name: Update package
  hosts: all
  become: yes
  vars:
    package_status: version
  #  package_name: ""
  #  package_version: ""
    service_status: restart
    #service_name: ""
  roles:
  - role: package_management
  - { role: service_management, when: "service_name != ''" }