---
- name: "Get {{ crontab_account }}"  
  shell: "/usr/bin/getent passwd {{ crontab_account }}"
  ignore_errors: yes
  register: account_info 

- name: "{{ crontab_account }} not found"
  debug:
    msg: "{{ crontab_account }} not found"
  when: account_info.rc != 0
  failed_when: account_info.rc != 0    